  GNU nano 8.7                         incus.nix                                    
{
  lib,
  config,
  pkgs,
  ...
}:

# WARNING: THIS CONFIGURATION IS AUTOGENERATED AND WILL BE OVERWRITTEN AUTOMATICALLY

{
  networking.hostName = "matrix";
}

