{ modulesPath, username, ... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
  ];

  # ── Networks ───────────────────────────────────────────────────────────────────
  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # ── Users ─────────────────────────────────────────────────────────────────────
  users.defaultUserShell = "/run/current-system/sw/bin/zsh";
  # Allow users to change their own passwords via the passwd command
  users.mutableUsers = true;
  users.users.${username} = {
    isNormalUser = true;
    description = "${username}";
    extraGroups = [
      "wheel"
    ];
    shell = "/run/current-system/sw/bin/zsh";
  };

  system.stateVersion = "26.05";
}

